// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoOtH1UNS_NLnyJQOAVOcp5RX1bLmbkQE',
    appId: '1:254564875028:web:35af67f96e03876a962001',
    messagingSenderId: '254564875028',
    projectId: 'my-test-project-f91ed',
    authDomain: 'my-test-project-f91ed.firebaseapp.com',
    storageBucket: 'my-test-project-f91ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-kdUQZ1a5GvdwLMoRpIK8An7U9tq1YvY',
    appId: '1:254564875028:android:eff9e4a6f39ab142962001',
    messagingSenderId: '254564875028',
    projectId: 'my-test-project-f91ed',
    storageBucket: 'my-test-project-f91ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHetsGdSsXbU--nx2kcgjq-u8ugow3I8',
    appId: '1:254564875028:ios:e348c30214293a7a962001',
    messagingSenderId: '254564875028',
    projectId: 'my-test-project-f91ed',
    storageBucket: 'my-test-project-f91ed.appspot.com',
    iosBundleId: 'com.raasithprojects.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASHetsGdSsXbU--nx2kcgjq-u8ugow3I8',
    appId: '1:254564875028:ios:40b0b66981d88856962001',
    messagingSenderId: '254564875028',
    projectId: 'my-test-project-f91ed',
    storageBucket: 'my-test-project-f91ed.appspot.com',
    iosBundleId: 'com.raasithprojects.pushNotification.RunnerTests',
  );
}
